# Translations template for murano.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the murano project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: murano 2.0.0.0rc2.dev91\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-19 06:30+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: murano/utils.py:37
msgid "Environment with id {env_id} not found"
msgstr ""

#: murano/utils.py:44
msgid "User is not authorized to access these tenant resources"
msgstr ""

#: murano/utils.py:54
msgid "Session <SessionId {id}> is not found"
msgstr ""

#: murano/utils.py:59
msgid ""
"Session <SessionId {session_id}> is not tied with Environment <EnvId "
"{environment_id}>"
msgstr ""

#: murano/utils.py:83
msgid "Environment Template with id {id} not found"
msgstr ""

#: murano/utils.py:90
msgid "User is not authorized to access this tenant resources"
msgstr ""

#: murano/utils.py:103
msgid "X-Configuration-Session header which indicates to the session is missed"
msgstr ""

#: murano/utils.py:114
msgid "Session <SessionId {0}> is not found"
msgstr ""

#: murano/utils.py:119 murano/api/v1/sessions.py:76
#: murano/api/v1/sessions.py:122
msgid ""
"Session <SessionId {0}> is invalid: environment has been updated or "
"updating right now with other session"
msgstr ""

#: murano/utils.py:126
msgid "Session <SessionId {0}> is already in deployment state"
msgstr ""

#: murano/api/middleware/context.py:25
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: murano/api/middleware/ext_context.py:100
msgid "Authorization required"
msgstr ""

#: murano/api/middleware/ext_context.py:104
msgid "Your credentials are wrong. Please try again"
msgstr ""

#: murano/api/v1/actions.py:75
msgid ""
"Result for task with environment_id: {env_id} and task_id: {task_id} was "
"not found."
msgstr ""

#: murano/api/v1/catalog.py:55
msgid "Content-Type must be '{type}'"
msgstr ""

#: murano/api/v1/catalog.py:97
msgid "Uploading file is too large. The limit is {0} Mb"
msgstr ""

#: murano/api/v1/catalog.py:102
msgid ""
"'multipart/form-data' request body should contain 1 or 2 parts: json "
"string and zip archive. Current body consists of {amount} part(s)"
msgstr ""

#: murano/api/v1/catalog.py:118
msgid "There is no file package with application description"
msgstr ""

#: murano/api/v1/catalog.py:133
msgid "Limit param must be an integer"
msgstr ""

#: murano/api/v1/catalog.py:138
msgid "Limit param must be positive"
msgstr ""

#: murano/api/v1/catalog.py:164
msgid "Request body must be a JSON array of operation objects."
msgstr ""

#: murano/api/v1/catalog.py:173 murano/api/v1/catalog.py:250
msgid "Package name should be 80 characters maximum"
msgstr ""

#: murano/api/v1/catalog.py:222
msgid "Package schema is not valid: {reason}"
msgstr ""

#: murano/api/v1/catalog.py:236
msgid "Uploading file can't be empty"
msgstr ""

#: murano/api/v1/catalog.py:257
msgid "Package with specified full name is already registered"
msgstr ""

#: murano/api/v1/catalog.py:263
msgid "Couldn't load package from file: {reason}"
msgstr ""

#: murano/api/v1/catalog.py:341
msgid "Bad value passed to filter. Got {key}, exected:{valid}"
msgstr ""

#: murano/api/v1/catalog.py:351
msgid "Invalid sort key: {sort_key}. Must be one of the following: {available}"
msgstr ""

#: murano/api/v1/catalog.py:358
msgid "Invalid sort direction: {0}"
msgstr ""

#: murano/api/v1/catalog.py:387
msgid "Category name should be 80 characters maximum"
msgstr ""

#: murano/api/v1/catalog.py:393
msgid "Category with specified name is already exist"
msgstr ""

#: murano/api/v1/catalog.py:403
msgid ""
"It's impossible to delete categories assigned to the package, uploaded to"
" the catalog"
msgstr ""

#: murano/api/v1/environments.py:68
msgid "Please, specify a name of the environment to create"
msgstr ""

#: murano/api/v1/environments.py:74 murano/api/v1/environments.py:135
msgid "Environment name should be 255 characters maximum"
msgstr ""

#: murano/api/v1/environments.py:82 murano/api/v1/environments.py:142
#: murano/api/v1/templates.py:192 murano/api/v1/templates.py:242
msgid "Environment with specified name already exists"
msgstr ""

#: murano/api/v1/environments.py:146
msgid "Environment name must contain at least one non-white space symbol"
msgstr ""

#: murano/api/v1/services.py:72 murano/api/v1/services.py:95
msgid "Request body is empty: please, provide application object model"
msgstr ""

#: murano/api/v1/sessions.py:46
msgid ""
"Could not open session for environment <EnvId: {env_id}>, environment has"
" deploying status."
msgstr ""

#: murano/api/v1/sessions.py:69 murano/api/v1/sessions.py:95
msgid ""
"User <UserId {usr_id}> is not authorized to access session <SessionId "
"{s_id}>."
msgstr ""

#: murano/api/v1/sessions.py:102
msgid "Session <SessionId: {s_id}> is in deploying state and could not be deleted"
msgstr ""

#: murano/api/v1/sessions.py:129
msgid ""
"Session <SessionId {s_id}> is already deployed or deployment is in "
"progress"
msgstr ""

#: murano/api/v1/template_applications.py:69
msgid "The environment template {templ_id} does not exist"
msgstr ""

#: murano/api/v1/template_applications.py:93
#: murano/api/v1/template_applications.py:121
#: murano/api/v1/template_applications.py:151
#: murano/api/v1/template_applications.py:174
msgid "The template does not exist {templ_id}"
msgstr ""

#: murano/api/v1/templates.py:88
msgid "Env Template with specified name already exists"
msgstr ""

#: murano/api/v1/templates.py:132
msgid "Environment Template must contain at least one non-white space symbol"
msgstr ""

#: murano/api/v1/templates.py:137
msgid "EnvTemplate body is incorrect"
msgstr ""

#: murano/api/v1/templates.py:262
msgid "EnvTemplate <TempId {temp_id}> is not found"
msgstr ""

#: murano/api/v1/templates.py:272
msgid "Please, specify a name of the environment template."
msgstr ""

#: murano/api/v1/templates.py:278
msgid "Environment template name should be 255 characters maximum"
msgstr ""

#: murano/api/v1/cloudfoundry/cfapi.py:34
msgid "Project for service broker"
msgstr ""

#: murano/api/v1/cloudfoundry/cfapi.py:36
msgid "Host for service broker"
msgstr ""

#: murano/api/v1/cloudfoundry/cfapi.py:38
msgid "Port for service broker"
msgstr ""

#: murano/api/v1/cloudfoundry/cfapi.py:40
msgid "Authentication URL"
msgstr ""

#: murano/api/v1/cloudfoundry/cfapi.py:42
msgid "Domain name of the user"
msgstr ""

#: murano/api/v1/cloudfoundry/cfapi.py:44
msgid "Domain name of the project"
msgstr ""

#: murano/cmd/test_runner.py:75
msgid ""
"Local package is not found since \"load-packages-from\" engine parameter "
"is not provided and specified packages is not loaded to murano-api"
msgstr ""

#: murano/cmd/test_runner.py:79
msgid ""
"Specified package is not found: {0} were scanned together with murano "
"database"
msgstr ""

#: murano/cmd/test_runner.py:222
msgid "No tests found for execution."
msgstr ""

#: murano/common/app_loader.py:55
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr ""

#: murano/common/app_loader.py:89
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s. \n"
"Got: %(e)r"
msgstr ""

#: murano/common/config.py:201
msgid "Statistics collection interval in minutes.Default value is 5 minutes."
msgstr ""

#: murano/common/config.py:207
msgid "Disallow the use of murano-agent"
msgstr ""

#: murano/common/config.py:209
msgid "Path to class configuration files"
msgstr ""

#: murano/common/config.py:211
msgid "Create resources using trust token rather than user's token"
msgstr ""

#: murano/common/config.py:214
msgid "Enable model policy enforcer using Congress"
msgstr ""

#: murano/common/config.py:216
msgid "Time for waiting for a response from murano agent during the deployment"
msgstr ""

#: murano/common/config.py:219
msgid "Number of workers"
msgstr ""

#: murano/common/config.py:222
msgid ""
"List of directories to load local packages from. If not provided, "
"packages will be loaded only API"
msgstr ""

#: murano/common/config.py:231
msgid ""
"Enables murano-engine to persist on disk packages downloaded during "
"deployments. The packages would be re-used for consequent deployments."
msgstr ""

#: murano/common/config.py:238
msgid ""
"The service to store murano packages: murano (stands for legacy behavior "
"using murano-api) or glance (stands for glance-glare artifact service)"
msgstr ""

#: murano/common/utils.py:75 murano/common/utils.py:137
msgid "Source object or path is malformed"
msgstr ""

#: murano/common/wsgi.py:115
#, python-format
msgid ""
"Could not bind to %(host)s:%(port)s after trying for 30 seconds: Address "
"already in use."
msgstr ""

#: murano/common/wsgi.py:370
msgid "Exception handling resource: {0}"
msgstr ""

#: murano/common/wsgi.py:419
msgid "Unsupported Content-Type"
msgstr ""

#: murano/common/wsgi.py:422
msgid "Acceptable response can not be provided"
msgstr ""

#: murano/common/wsgi.py:425
msgid "Malformed request body"
msgstr ""

#: murano/common/wsgi.py:828 murano/common/wsgi.py:848
msgid "cannot understand JSON"
msgstr ""

#: murano/common/wsgi.py:854
msgid "Operations must be JSON objects."
msgstr ""

#: murano/common/wsgi.py:870
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr ""

#: murano/common/wsgi.py:878 murano/common/wsgi.py:885
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr ""

#: murano/common/wsgi.py:894
msgid "Attribute '{0}' is invalid"
msgstr ""

#: murano/common/wsgi.py:898
msgid ""
"Method '{method}' is not allowed for a path with name '{name}'. Allowed "
"operations are: '{ops}'"
msgstr ""

#: murano/common/wsgi.py:939
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr ""

#: murano/common/wsgi.py:942
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: murano/common/wsgi.py:945
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: murano/common/wsgi.py:948
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: murano/common/wsgi.py:951
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""

#: murano/common/wsgi.py:964
msgid "Nested paths are not allowed"
msgstr ""

#: murano/common/wsgi.py:988
msgid "cannot understand XML"
msgstr ""

#: murano/db/catalog/api.py:48
msgid "Package id '{pkg_id}' not found"
msgstr ""

#: murano/db/catalog/api.py:59
msgid "Package '{pkg_id}' is not owned by tenant '{tenant}'"
msgstr ""

#: murano/db/catalog/api.py:65
msgid "Package '{pkg_id}' is not public and not owned by tenant '{tenant}' "
msgstr ""

#: murano/db/catalog/api.py:98
msgid "Category '{name}' doesn't exist"
msgstr ""

#: murano/db/catalog/api.py:211
msgid "Value '{value}' of property '{path}' does not exist."
msgstr ""

#: murano/db/catalog/api.py:447 murano/db/catalog/api.py:501
msgid "Category id '{id}' not found"
msgstr ""

#: murano/db/catalog/api.py:534
msgid ""
"Class with the same full name is already registered in the visibility "
"scope"
msgstr ""

#: murano/db/catalog/api.py:548
msgid "Package with the same Name is already made public"
msgstr ""

#: murano/db/services/core_services.py:91
#: murano/db/services/core_services.py:111
msgid "Environment Template <EnvId {id}> is not found"
msgstr ""

#: murano/db/services/core_services.py:141
#: murano/db/services/core_services.py:222
msgid "Environment Template <EnvId {0}> is not found"
msgstr ""

#: murano/db/services/core_services.py:167
msgid "Environment <EnvId {0}> is not found"
msgstr ""

#: murano/db/services/environment_templates.py:74
msgid "Environment template specified name already exists"
msgstr ""

#: murano/packages/package_base.py:138
msgid "{0}: Unsupported Format. Only {1} allowed"
msgstr ""

#: murano/packages/package_base.py:145
msgid "{0}: Uploaded image size {1} is too large. Max allowed size is {2}"
msgstr ""

#: murano/policy/model_policy_enforcer.py:127
msgid "Murano object model validation failed: {0}"
msgstr ""

